### ISSUE TITLE
Some types of JOIN's break the parser

### ISSUE THREAD

**Issue by techedemic** [godmodelabs/flora-sql-parser#17]
Firstly, thanks for this tool/module...it helps a lot.

Given the following SQL statement, the parser works fine:
```sql
SELECT m.userId, m.username, m.email, a.isAdmin
FROM member m
LEFT JOIN admin a ON m.id = a.id
```

The following, however, fails.
```sql
SELECT m.userId, m.username, m.email, a.isAdmin
FROM member m
LEFT OUTER JOIN admin a ON m.id = a.id
```
My code is as follows
```javascript
var sql = "SELECT m.id, m.username, m.email, a.isAdmin ";
sql += "FROM member m "
sql += "LEFT OUTER JOIN admin a ON m.id = a.id"

const Parser = require('flora-sql-parser').Parser;
const parser = new Parser();
const ast = parser.parse(sql);

console.log(ast);
```

The error is as follows:
```bash
/home/user/Projects/node/mysqltest/node_modules/flora-sql-parser/pegjs-parser.js:10194
    throw peg$buildStructuredError(
    ^
SyntaxError: Expected "--", "/*", "JOIN", or [ \t\n\r] but "O" found.
    at peg$buildStructuredError (/home/user/Projects/node/mysqltest/node_modules/flora-sql-parser/pegjs-parser.js:949:12)
    at peg$parse (/home/user/Projects/node/mysqltest/node_modules/flora-sql-parser/pegjs-parser.js:10194:11)
    at Parser.parse (/home/user/Projects/node/mysqltest/node_modules/flora-sql-parser/lib/parser.js:7:16)
    at Object.<anonymous> (/home/user/Projects/node/mysqltest/parser.js:7:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
```

**Comment by mbaumgartl** [comment]
OUTER is optional in left, right and full joins. The keyword was not supported by the parser until 0.7.7.
